name: application-cicd-dev

# Controls when the workflow will run
on:
  push:
    paths: 
      - 'MLOps_4/src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MLOps_4/src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --exclude=__init__.py

      - name: Check code formatting with Black
        run: black . --check --diff

      - name: Run unit tests
        run: |
          pytest tests/
  build:
    needs: test-lint
    runs-on: ubuntu-latest
    environment: AWS
    defaults:
      run:
        working-directory: MLOps_4/src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Pull latest data with DVC
        run: dvc pull

      - name: Retrain model
        run: python main.py
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build, tag, and push docker image to Amazon ECR 
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
